# Generated by Django 5.1.5 on 2025-01-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_negotiation_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_details', to='supplier_negotiation_chatbot.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('incoterms', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('FAS', 'FAS'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('CPT', 'CPT'), ('CIP', 'CIP'), ('DAP', 'DAP'), ('DPU', 'DPU'), ('DDP', 'DDP')], default='EXW', max_length=10)),
                ('payment_terms', models.CharField(choices=[('30_days', '30 days'), ('60_days', '60 days'), ('90_days', '90 days'), ('L/C', 'Letter of Credit')], default='30_days', max_length=10)),
                ('delivery_time', models.CharField(choices=[('1_week', '1 week'), ('2_weeks', '2 weeks'), ('1_month', '1 month'), ('2_months', '2 months')], default='2_weeks', max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_cost', models.CharField(choices=[('buyer', 'Buyer'), ('supplier', 'Supplier'), ('shared', 'Shared')], default='buyer', max_length=10)),
                ('warranty_terms', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('quality_specifications', models.TextField(blank=True, null=True)),
                ('volume_discount_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxes_and_customs', models.TextField(blank=True, null=True)),
                ('after_sales_support', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=50)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiated_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiated_bundling_quantity_discount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiated_bundling_price_discount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiated_bundling_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('negotiated_payment_terms', models.CharField(blank=True, choices=[('30_days', '30 days'), ('60_days', '60 days'), ('90_days', '90 days'), ('L/C', 'Letter of Credit')], max_length=10, null=True)),
                ('negotiated_delivery_time', models.CharField(blank=True, choices=[('1_week', '1 week'), ('2_weeks', '2 weeks'), ('1_month', '1 month'), ('2_months', '2 months')], max_length=10, null=True)),
                ('negotiated_contract_length', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('negotiated_contract_inflation', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('negotiated_rebate_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiated_rebate_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('negotiated_warranty_period', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('negotiated_incoterms', models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('FAS', 'FAS'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('CPT', 'CPT'), ('CIP', 'CIP'), ('DAP', 'DAP'), ('DPU', 'DPU'), ('DDP', 'DDP')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_negotiation_chatbot.material')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AddField(
            model_name='conversation',
            name='negotiation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier_negotiation_chatbot.negotiation'),
        ),
    ]
